baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Apicentar Kosmaj'
watch = true
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2