baseURL = 'https://example.org/'
languageCode = 'sr'
title = 'Апицентар Космај - Апитерапија у служби здравља'
# START --> Internacionalization configuration block.

defaultContentLanguage = "sr"
[languages]
  [languages.sr]
    languageName = "Српски"
    weight = 1
    contentDir = "content/sr"
    title = "Апицентар Космај - Апитерапија у служби здравља"

    [[languages.sr.menu.main]]
    name = "Почетна"
    url = "/"
    weight = 1

    [[languages.sr.menu.main]]
    name = "Терапије"
    url = "/therapies/"
    weight = 2

    [[languages.sr.menu.main]]
    name = "Услуге"
    url = "/services/"
    weight = 3

    [[languages.sr.menu.main]]
    name = "Галерија"
    url = "/gallery/"
    weight = 4

    [[languages.sr.menu.main]]
    name = "Ценовник"
    url = "/pricing/"
    weight = 5

    [[languages.sr.menu.main]]
    name = "О нама"
    url = "/about/"
    weight = 6

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    title = "Apitherapy center Kosmaj - Apitherapy in the service of health"

    [[languages.en.menu.main]]
    name = "Home"
    url = "/en/"
    weight = 1

    [[languages.en.menu.main]]
    name = "Therapies"
    url = "/en/therapies/"
    weight = 2

    [[languages.en.menu.main]]
    name = "Services"
    url = "/en/services/"
    weight = 3

    [[languages.en.menu.main]]
    name = "Gallery"
    url = "/en/gallery/"
    weight = 4

    [[languages.en.menu.main]]
    name = "Pricing"
    url = "/en/pricing/"
    weight = 5

    [[languages.en.menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 6

# END <-- Internacionalization configuration block.
